### ISSUE TITLE
Removing unused imports

### ISSUE THREAD

**Issue by Chetan11-dev** [fluttercommunity/import_sorter#15]
FIRST OF ALL THANKS FOR THE AMAZING PACKAGE
It would be great if you could add feature of removing unused imports like https://marketplace.visualstudio.com/items?itemName=luanpotter.dart-import

**Comment by Matt-Gleich** [comment]
Thank you so much for the kind words! Although this would be a nice feature I have no idea how it could be done without adding a ton of code to the little package. Let me know if you know of a way to parse the file and check if certain classes and functions are being used from that other file. For now, because I have no plans to implement this in the immediate future, I am going to close this issue.
